import React, { FC, useState } from 'react';

import {
    Modal,
    ModalContent,
    ConsentWindow,
    Title,
    MainText,
    CheckboxContainer,
    Input,
    StyledCheckbox,
    Icon,
    Label,
    Span,
    ContinueButton,
    ButtonText,
} from './Consent.styles';
import { createPortal } from 'react-dom';

type Props = {
    show: boolean;
    onClose: () => void;
};

export const ConsentModal: FC<Props> = (props) => {
    const { show, onClose } = props;

    const [isChecked, setIsChecked] = useState<boolean>(false);

    return createPortal(
        <div>
            <Modal $show={show} onClick={onClose} />
            <ModalContent $show={show}>
                <ConsentWindow>
                    <Title>About the platform</Title>
                    <MainText>
                        All of the characters here are not real. Everything you see and hear is
                        entirely generated by Artificial Intelligence machines. The opinions and
                        beliefs expressed do not represent anyone. They are hallucinations of a
                        bunch of 1s and 0s inside of a magic computer.
                    </MainText>
                    <MainText>
                        The creators of this platform have the best intentions with this project,
                        and deeply admire each and every character on the site. You might even say
                        they are our Heroes. In fact, you can say that.
                    </MainText>
                    <CheckboxContainer>
                        <Label>
                            <Input
                                checked={isChecked}
                                onChange={(event) => setIsChecked(event.target.checked)}
                            />
                            <StyledCheckbox checked={isChecked} tabIndex={0}>
                                <Icon
                                    checked={isChecked}
                                    width="18"
                                    height="13"
                                    viewBox="0 0 18 13"
                                    fill="none"
                                    xmlns="http://www.w3.org/2000/svg"
                                >
                                    {' '}
                                    <path
                                        d="M17 1L6 12L1 7"
                                        stroke="white"
                                        strokeWidth="1.5"
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                    />
                                </Icon>
                            </StyledCheckbox>
                            <Span>I have read the above statement</Span>
                        </Label>
                    </CheckboxContainer>
                    <ContinueButton disabled={!isChecked}>
                        <ButtonText>CONTINUE</ButtonText>
                    </ContinueButton>
                </ConsentWindow>
            </ModalContent>
        </div>,
        document.getElementById('root') as HTMLElement,
    );
};
