export const souls = [
    {
        id: 1,
        name: 'Dr. Martin Luther King Jr.',
        title: 'Political Activist',
        src: '/main/souls/King.png',
        alt: 'King',
    },
    {
        id: 2,
        name: 'Steve Jobs',
        title: 'Apple Computer Founder',
        src: '/main/souls/Jobs.png',
        alt: 'Jobs',
    },
    {
        id: 3,
        name: 'Elon Musk',
        title: 'Space nerd',
        src: '/main/souls/Musk.png',
        alt: 'Musk',
    },
    {
        id: 4,
        name: 'Albert Einstein',
        title: 'Genius',
        src: '/main/souls/Einstein.png',
        alt: 'Einstein',
    },
    {
        id: 5,
        name: 'Mother Teresa',
        title: 'Philanthropist',
        src: '/main/souls/Teresa.png',
        alt: 'Teresa',
    },
    {
        id: 6,
        name: 'Jesus Christ',
        title: 'Lord & Savior',
        src: '/main/souls/Jesus.png',
        alt: 'Jesus',
    },
    {
        id: 7,
        name: 'Leonardo Da Vinci',
        title: 'Artist',
        src: '/main/souls/Davinci.png',
        alt: 'Davinci',
    },
    {
        id: 8,
        name: 'Queen Elizabeth',
        title: 'Queen of England',
        src: '/main/souls/Queen.png',
        alt: 'Queen',
    },
    {
        id: 9,
        name: 'William Shakespeare',
        title: 'Author',
        src: '/main/souls/Shakespeare.png',
        alt: 'Shakespeare',
    },
    {
        id: 10,
        name: 'Nelson Mandela',
        title: 'Philanthropist',
        src: '/main/souls/Mandela.png',
        alt: 'Mandela',
    },
    {
        id: 11,
        name: 'Betsy Ross',
        title: 'American history',
        src: '/main/souls/Ross.png',
        alt: 'Ross',
    },
    {
        id: 12,
        name: 'Ghandi',
        title: 'Philanthropist',
        src: '/main/souls/Ghandi.png',
        alt: 'Ghandi',
    },
    {
        id: 13,
        name: 'Abraham Lincoln',
        title: 'American president',
        src: '/main/souls/Lincoln.png',
        alt: 'Lincoln',
    },
    {
        id: 14,
        name: 'Ron Swanson',
        title: 'TV goofy guy',
        src: '/main/souls/Swanson.png',
        alt: 'Swanson',
    },
];
